services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY:?Falta SECRET_KEY en el fichero .env}
      ADMIN_EMAIL: ${ADMIN_EMAIL:?Falta ADMIN_EMAIL en el fichero .env}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Falta ADMIN_PASSWORD en el fichero .env}
    volumes:
      - datos:/data

volumes:
  datos:

